---
- name: Install Jenkins
  hosts: jenkins
  become: true

  tasks:
    - name: Update apt
      apt:
        update_cache: true

    - name: create jenkins docker network
      shell: |
        docker network create jenkins

    - name: create jenkins docker
      shell: |
        docker run \
        --name jenkins-docker \
        --detach \
        --privileged \
        --network jenkins \
        --network-alias docker \
        --env DOCKER_TLS_CERTDIR=/certs \
        --volume jenkins-docker-certs:/certs/client \
        --volume jenkins-data:/var/jenkins_home \
        --publish 2376:2376 \
        docker:dind \
        --storage-driver overlay2

    - name: Copy a file to remote hosts
      copy:
        src: /home/vagrant/ansible/Dockerfile
        dest: /home/vagrant/Dockerfile
        owner: vagrant
        group: vagrant
        mode: "0644"

    - name: create from Dockerfile
      shell: |
        docker build -t myjenkins-blueocean:2.528.3-1 .

    - name: create web jenkins docker
      shell: |
        docker run \
        --name jenkins-blueocean \
        --restart=on-failure \
        --detach \
        --network jenkins \
        --env DOCKER_HOST=tcp://docker:2376 \
        --env DOCKER_CERT_PATH=/certs/client \
        --env DOCKER_TLS_VERIFY=1 \
        --publish 8080:8080 \
        --publish 50000:50000 \
        --volume jenkins-data:/var/jenkins_home \
        --volume jenkins-docker-certs:/certs/client:ro \
        myjenkins-blueocean:2.528.3-1