---
- name: Install Minikube kubectl
  hosts: slave
  become: true

  tasks:
    - name: Update apt
      apt:
        update_cache: true

    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.35.0/bin/linux/amd64/kubectl
        dest: /vagrant/kubectl
        mode: '0755'

    - name: Install kubectl
      copy:
        src: /vagrant/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
        remote_src: yes

    - name: Download minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /vagrant/minikube
        mode: '0755'
      register: dl

    - name: Install minikube
      copy:
        src: /vagrant/minikube
        dest: /usr/local/bin/minikube
        mode: '0755'
        remote_src: yes
      when: dl.changed